version: 2.1

jobs:
  scan_full_repo:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout

      - run:
          name: Install ggshield
          command: pip install ggshield

      - run:
          name: Run full repo scan
          command: ggshield secret scan repo .

workflows:
  scan_my_commits:
    jobs:
      - scan_full_repo
